default: &default
  adapter: postgresql
  encoding: unicode
  username: ritika
  password: 1234
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_App_development

test:
  <<: *default
  database: Budget_App_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
